# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7ad7a3e69952ab3c5aad19d047b09abdec27983936468e61b4a16031d956b86092e5d91945e420f6c05ee9f5e68492c2f296af87c93e49d42c1fac17a9f6551

test:
  secret_key_base: 97c87a7dd0c65ae19d24599af80bc6d1672320fe9c760103eea2aa3675bb919eab233d73e00894c881202f0de2128d1c439483f758c2fa881d4aff55d6472cea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
